services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_RPC_URL: ${VITE_RPC_URL}
        VITE_FAUCET_ADDRESS: ${VITE_FAUCET_ADDRESS}
        VITE_TOKEN_ADDRESS: ${VITE_TOKEN_ADDRESS}
    ports:
      - "3000:80"
